# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_HOST: 3.110.208.56
      USER: ubuntu
      DEPLOY_FOLDER: healjour-fe-dev
      SERVER_SSH_KEY: ${{ secrets.HEALJOUR_FE_PROD_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm dependencies
        run: npm install

      - name: Run build task
        run: npm run build

      - name: Copy files before deploy
        run: node before_deploy.cjs

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HEALJOUR_FE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: 3.110.208.56
          REMOTE_USER: ubuntu
          TARGET: "~/healjour-fe-dev/"
          EXCLUDE: "/node_modules/"

      - name: RUN SERVER
        uses: appleboy/ssh-action@master #change back to master once docker issue get fixed by repo owner
        with:
          host: 3.110.208.56
          username: ubuntu
          key: ${{ secrets.HEALJOUR_FE_KEY }}
          script: sh ~/healjour-fe-dev/master.deploy.sh
