# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_HOST: 65.2.177.88
      USER: ubuntu
      DEPLOY_FOLDER: healjour-fe-dev
      SERVER_SSH_KEY: ${{ secrets.HEALJOUR_FE_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install npm dependencies
        run: npm install

      - name: Run build task
        run: npm run build

      - name: Copy files before deploy
        run: node before_deploy.cjs

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ env.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{env.AWS_HOST}}
          REMOTE_USER: ${{env.USER}}
        env:
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          TARGET: "~/${{env.DEPLOY_FOLDER}}/"
          EXCLUDE: "/node_modules/"

      - name: RUN SERVER
        uses: appleboy/ssh-action@master #change back to master once docker issue get fixed by repo owner
        with:
          host: ${{env.AWS_HOST}}
          username: ${{env.USER}}
          key: ${{ env.SERVER_SSH_KEY }}
          script: sh ~/${{env.DEPLOY_FOLDER}}/master.deploy.sh
